Add visual warning when the repository is archived
SwiftPackageIndex/SwiftPackageIndex-Server pull request #1174
Opened 2021-06-14 15:10 UTC by ricardopereira

In the package listing, in my opinion, it should visually warn the user when the repository has been archived by the owner. 

**Example:**

Before:
![Screenshot 2021-06-14 at 15 50 21](https://user-images.githubusercontent.com/3541185/121912161-3e261080-cd28-11eb-85df-cf5b16a3f344.png)

After (add a warning symbol):
![Screenshot 2021-06-14 at 15 48 00](https://user-images.githubusercontent.com/3541185/121911806-fb643880-cd27-11eb-8456-e3d0d504b1e6.png)

2021-06-14 22:12 UTC, daveverwer requested changes
Hey Ricardo, and thanks very much for this.

I think if we need to make this more obvious, I'd want to pull that text out into a separate line and use the icon that we have on the left-hand side of the list items to indicate it's important.

I'm tracking that now as #1175.

If you want to have a go at doing that, that'd be great. I can make the icon for you and add it once you have the text re-positioned. Let me know if you'd like to do that.

2021-06-15 09:48 UTC, ricardopereira commented
Thanks @daveverwer, I'll try do that. Something like this?

![Screenshot 2021-06-15 at 10 47 46](https://user-images.githubusercontent.com/3541185/122032018-281b5d00-cdc7-11eb-85aa-89290cb1657f.png)

2021-06-15 14:59 UTC, daveverwer commented
Yep, that looks great! I might tweak the icon to be different but I'd like to run it locally before deciding that. Could you push those changes to this branch please and I'll check it out.

Thanks!

2021-07-07 08:26 UTC, daveverwer commented
Thanks again for this @ricardopereira. I'm going to close this PR now as it's superseded by #1221 from @selichter!

Thanks to you both.

2021-07-07 08:26 UTC, closed without merging